### ISSUE TITLE
Add 'Off/not set' for high affinities instead of setting to 1000.

### ISSUE THREAD

**Issue by alisonrclarke** [DurhamARC/metalation-calculator#15]
Andrew said:

> Maybe in an ideal world you’d have an ‘off/not set’ button for the element but putting in a large value has the same effect.

Add a toggle button as the first column; if unchecked we can hide the values in that row but internally set the affinities to 1000.

**Comment by alisonrclarke** [comment]
Nigel has suggested adding a sentence of advice for what to do if affinity values are unknown to avoid interference: Andrew will provide details, but the details need to take into account that we've added a switch.

**Comment by alisonrclarke** [comment]
Latest update from Andrew:

> As long as the off/not set button sets affinity to 1000 M and buffered availability to the ideal cell value AND locks both cells so the user cannot change the values we think there is no need for explanatory text.

**Comment by zeynepaki** [comment]
- [ ] Add a toggle button (referred to as tb further down) to the left of X on each row
- [ ] Disable the input for the rows of which tb has been checked
- [ ] Display "-" for the input section for rows that have been disabled
- [ ] Internally set the affinities of rows to 1000 where tb has been checked
- [ ] Internally set the buffered availability to default values where tb has been checked

**Comment by zeynepaki** [comment]
okay I'll alter accordingly

**Comment by zeynepaki** [comment]
> Latest update from Andrew:
> 
> > As long as the off/not set button sets affinity to 1000 M and buffered availability to the ideal cell value AND locks both cells so the user cannot change the values we think there is no need for explanatory text.

Where can I find where the ideal cell values are set for the default values of buffered availability?

**Comment by zeynepaki** [comment]
> > Latest update from Andrew:
> > > As long as the off/not set button sets affinity to 1000 M and buffered availability to the ideal cell value AND locks both cells so the user cannot change the values we think there is no need for explanatory text.
> 
> Where can I find where the ideal cell values are set for the default values of buffered availability?

found it nvm
