### ISSUE TITLE
Tidy up SCSS

### ISSUE THREAD

**Issue by alisonrclarke** [DurhamARC/metalation-calculator#28]
I think there's probably a bit of refactoring we can do to make the SCSS a bit tidier, e.g. where classes related to table cells, we can  put their details inside the `td` or `th` sections. Might also be good to group similar areas together a bit more.

We should also add a linter for the SCSS to the gulp file and the CI: stylelint.io looks to be the most up-to-date linter; see https://www.npmjs.com/package/gulp-stylelint for a gulp package.

**Comment by zeynepaki** [comment]
I've nested the tooltip lines as much as I can but I'm not sure how to make this tidier


<img width="332" alt="Screenshot 2021-11-29 at 13 00 11" src="https://user-images.githubusercontent.com/73976500/143872707-bd9ef454-7b9d-4901-986d-6f08ad48d84d.png">

**Comment by zeynepaki** [comment]
https://www.npmjs.com/package/gulp-scss-lint 
Maybe this one for sass linter ?

**Comment by alisonrclarke** [comment]
> https://www.npmjs.com/package/gulp-scss-lint
> Maybe this one for sass linter ?

That package hasn't been updated for 3 years - probably better to use one that is still getting updates. I think the stylelint one I linked above should work for sass from what I read last week.

**Comment by alisonrclarke** [comment]
> I've nested the tooltip lines as much as I can but I'm not sure how to make this tidier
> 
> <img alt="Screenshot 2021-11-29 at 13 00 11" width="332" src="https://user-images.githubusercontent.com/73976500/143872707-bd9ef454-7b9d-4901-986d-6f08ad48d84d.png">

I think that's fine (other than linting) - see other comments on #31 for how to make further improvements.
