### ISSUE TITLE
Ensure CSS works with other CSS themes

### ISSUE THREAD

**Issue by alisonrclarke** [DurhamARC/metalation-calculator#29]
Testing the plugin in the default theme for Wordpress development shows a couple of issues:

 * [x] If the page background colour is not white, the spacing between the grouped columns doesn't match the row colour: we should specify a white background for rows by default
 * [x] If the page width is reduced the title wrapping doesn't always work as expected: we should add `white-space:nowrap` to the `sup` tags
 * [ ] The padding around the input elements should be fixed in the CSS

![Screenshot 2021-11-26 at 11 44 39](https://user-images.githubusercontent.com/4507639/143576306-21b52f8d-df3c-414a-9120-3edb90ff8a62.png)

Although we should concentrate on getting the calculator looking good with the current mib-nibb theme, we should take into account that the theme could change in future, or that others may want to use the plugin on their own site.

**Comment by zeynepaki** [comment]
the sup dat already has whitespace: nowrap

**Comment by alisonrclarke** [comment]
OK, I'll assign this back to myself once #31 is closed and I'll take a look at the superscripting next time I have things working in Wordpress. Must be something in the Wordpress theme that changes things.

**Comment by alisonrclarke** [comment]
I can't reproduce the issue with `<sup>` in Wordpress now. Maybe something else changed since I logged the issue!

**Comment by alisonrclarke** [comment]
Have added padding and margin to the inputs in the main calculator on the wp-style-fixes branch. @zeynepaki Does this look OK to you?

![Screenshot 2022-01-14 at 14 42 35](https://user-images.githubusercontent.com/4507639/149534734-999b2e1e-7b0b-4c3f-9459-c2b4053e03bf.png)

**Comment by zeynepaki** [comment]
> Have added padding and margin to the inputs in the main calculator on the wp-style-fixes branch. @zeynepaki Does this look OK to you?
> 
> ![Screenshot 2022-01-14 at 14 42 35](https://user-images.githubusercontent.com/4507639/149534734-999b2e1e-7b0b-4c3f-9459-c2b4053e03bf.png)

I think it looks absolutely fine
