### ISSUE TITLE
Fix affinity units

### ISSUE THREAD

**Issue by alisonrclarke** [DurhamARC/metalation-calculator#40]
Should be M not M^-1.

**Comment by zeynepaki** [comment]
<img width="869" alt="Screenshot 2022-01-06 at 14 46 49" src="https://user-images.githubusercontent.com/73976500/148385240-f8b5d548-d13b-47d4-b1ed-e736d0872950.png">
Just checked this now, isn't it already M and not M^-1 ? Am I looking at the wrong thing ? @alisonrclarke

**Comment by alisonrclarke** [comment]
You're right - I'd assumed from the email thread that we had the wrong units and opened the issue without checking! Will close it now.
