### ISSUE TITLE
Minor text edit on calculator

### ISSUE THREAD

**Issue by awf100** [DurhamARC/metalation-calculator#52]
CALCULATOR TEXT EDIT

metalation state of a protein or molecule

to 

metalation state of a protein or other biomolecule

**Comment by alisonrclarke** [comment]
![Screenshot 2022-02-22 at 11 35 42](https://user-images.githubusercontent.com/4507639/155124541-235ce741-cda8-40a3-a030-ac11d00d9d52.png)

Does this look OK @awf100 ?

**Comment by awf100** [comment]
Perfect, thanks Alison
