### ISSUE TITLE
Ensure calculator is usable on mobile devices

### ISSUE THREAD

**Issue by alisonrclarke** [DurhamARC/metalation-calculator#65]
On the mid-nibb webspace, the table collapses on small screens so that users can't see what's what. We should try adding labels to cells that are only visible if the screen is small, and fix the spacing.

![IMG_6E1C2542EA99-1](https://user-images.githubusercontent.com/4507639/166452944-9b860b05-b660-4687-a82b-b37dbc03e2ac.jpeg)

**Comment by alisonrclarke** [comment]
Some changes on my local instance. @zeynepaki @awf100 Does this look OK to you both?

![Screenshot 2022-06-09 at 10 47 22](https://user-images.githubusercontent.com/4507639/172818998-1e966f25-04f4-43c4-9c0d-e32e12c3437a.png)

![Screenshot 2022-06-09 at 10 47 33](https://user-images.githubusercontent.com/4507639/172819004-35cd92ae-c0c2-4aee-90cd-12d676ee53c9.png)

**Comment by awf100** [comment]
Hi Alison

This looks good to me, should make using the calculator on a mobile device far easier.
Many thanks

Andrew

**Comment by awf100** [comment]
Super – this is great – Nigel

From: FOSTER, ANDREW W. ***@***.***>
Sent: 13 June 2022 08:26
To: 'DurhamARC/metalation-calculator' ***@***.***>; DurhamARC/metalation-calculator ***@***.***>
Cc: Mention ***@***.***>; ROBINSON, NIGEL ***@***.***>
Subject: RE: [DurhamARC/metalation-calculator] Ensure calculator is usable on mobile devices (Issue #65)

Hi Alison

This looks good to me, should make using the calculator on a mobile device far easier.
Many thanks

Andrew

**Comment by alisonrclarke** [comment]
Thanks for the feedback. It needs a bit more work to ensure it’s compatible with the Wordpress theme but I’ll try to get that done this week.
